- name: Detect Debian version
  set_fact:
    debian_version: "{{ ansible_distribution_major_version }}"

- name: Overwrite /etc/apt/sources.list with Nexus repos
  copy:
    dest: /etc/apt/sources.list
    content: |
      {% for repo in debian_repos[debian_version] %}
      {{ repo }}
      {% endfor %}
    owner: root
    group: root
    mode: '0644'
  notify: apt-update



