- name: Detect Oracle Linux major version
  set_fact:
    oracle_version: "{{ ansible_distribution_major_version }}"

- name: Remove old YUM repo files
  file:
    path: /etc/yum.repos.d
    state: absent

- name: Recreate yum.repos.d directory
  file:
    path: /etc/yum.repos.d
    state: directory
    mode: '0755'

- name: Copy correct Nexus repo for Oracle Linux
  copy:
    src: "files/oracle-linux-{{ oracle_version }}.repo"
    dest: /etc/yum.repos.d/oracle-linux.repo
    owner: root
    group: root
    mode: '0644'

- name: Clean yum metadata
  command: yum clean all
